/**
 * 12 chromatic note samples (C3 - B3) generated by
 * apps/mobile/scripts/gen_chord_samples.py via Karplus-Strong synthesis.
 *
 * Bundled at build time through `require()`. Index 0 = C, 1 = C#, ..., 11 = B.
 */

export const NOTE_SAMPLES = [
  require("../../../../assets/samples/notes/note_C.wav"),
  require("../../../../assets/samples/notes/note_Csharp.wav"),
  require("../../../../assets/samples/notes/note_D.wav"),
  require("../../../../assets/samples/notes/note_Dsharp.wav"),
  require("../../../../assets/samples/notes/note_E.wav"),
  require("../../../../assets/samples/notes/note_F.wav"),
  require("../../../../assets/samples/notes/note_Fsharp.wav"),
  require("../../../../assets/samples/notes/note_G.wav"),
  require("../../../../assets/samples/notes/note_Gsharp.wav"),
  require("../../../../assets/samples/notes/note_A.wav"),
  require("../../../../assets/samples/notes/note_Asharp.wav"),
  require("../../../../assets/samples/notes/note_B.wav"),
];

/** Default fallback source — used by useAudioPlayer at init before play(). */
export const DEFAULT_SAMPLE = NOTE_SAMPLES[0];
